/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class InsertionTest {
    @Test public void testInsertionInt() {
        int[] params = {3, 1, 2};
        Insertion s = new Insertion();
        int[] expected = {1, 2, 3};
        s.sort(params);
        assertArrayEquals(
            expected,
            params
        );
    }
}
