/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class MergeTest {
    @Test public void testMergeInt() {
        
        Comparable[] params = new Comparable[3];
        params[0] = 3;
        params[1] = 2;
        params[2] = 1;

        Comparable[] expected = new Comparable[3];
        expected[0] = 1;
        expected[1] = 2;
        expected[2] = 3;

        Merge.sort(params);
        assertEquals(
            expected,
            params
        );
    }
}
