/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.*;

public class PercolationTest {
    @Test public void testBasicPercolation() {
        Percolation pc = new Percolation(2);
        assertFalse(pc.percolates());
        assertFalse(pc.isOpen(1, 1));
        assertFalse(pc.isFull(1, 1));
        assertFalse(pc.isFull(2, 1));
        
        pc.open(1, 1);
        assertTrue(pc.isOpen(1, 1));
        pc.open(2, 1);
        assertTrue(pc.percolates());
    }

    @Test(expected = IllegalArgumentException.class) public void testIllegalArgumentExceprion() {
        Percolation pc = new Percolation(0);
        pc.open(2, 1);
    }

    @Test(expected = IndexOutOfBoundsException.class) public void testIndexOutOfBoundsExceptionOnIsFull() {
        Percolation pc = new Percolation(2);
        pc.isFull(-1, 2);
    }

    @Test(expected = IndexOutOfBoundsException.class) public void testIndexOutOfBoundsExceptionOnIsOpen() {
        Percolation pc = new Percolation(2);
        pc.isOpen(100, 2000);
    }
}
