/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import edu.princeton.cs.algs4.StdDraw;
import static org.junit.Assert.*;

public class PointTest {
    @Test public void testBasicPoint() {
        Point p = new Point(100, 200);

        assertEquals(
            "100,200",
            p.toString()
        );

        Point p1 = new Point(3, 2);
        Point p2 = new Point(7, 8);

        double s = p1.slopeTo(p2);
        assertEquals(
            1.5,
            s,
            0.2
        );
    }

    @Test public void testDraw() {

        Point[] points = new Point[4];

        points[0] = new Point(100, 200);
        points[1] = new Point(3, 2);
        points[2] = new Point(7, 8);
        points[3] = new Point(100, 100);

        StdDraw.enableDoubleBuffering();
        StdDraw.setXscale(0, 200);
        StdDraw.setYscale(0, 200);
        for (Point p : points) {
            p.draw();
        }

        points[0].drawTo(points[3]);
        StdDraw.show();
    }
}
