/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class SelectionTest {
    @Test public void testSelectionInt() {
        int[] params = {3, 1, 2};
        Selection s = new Selection();
        int[] expected = {1, 2, 3};
        s.sort(params);
        assertArrayEquals(
            expected,
            params
        );
    }
}
